apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels: # label the pod
      app: moderation
  template: # specify configuration of the pod
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: etokatlian/moderation
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  type: ClusterIP
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
